# Generated by Django 5.1.4 on 2025-01-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('director', models.TextField()),
                ('main_actor', models.TextField()),
                ('genre', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('running_time', models.PositiveIntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
