# Generated by Django 5.1.4 on 2025-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller')], max_length=20),
        ),
    ]
