# Generated by Django 5.1.4 on 2025-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('comedy', '코미디'), ('drama', '드라마'), ('fantasy', '판타지'), ('horror', '공포'), ('romance', '로맨스'), ('sci-fi', '공상과학'), ('thriller', '스릴러')], max_length=20),
        ),
    ]
