# Generated by Django 4.2.2 on 2025-01-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='idea_images/')),
                ('content', models.TextField()),
                ('interest', models.PositiveIntegerField(default=0)),
                ('devtools', models.ManyToManyField(related_name='ideas', to='devtool.devtool')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(default=False)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='idea.idea')),
            ],
        ),
    ]
